{{- if .Values.opa -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opa.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
{{ include "opa.labels.standard" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.opa | b64enc }}
---
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
{{- if .Values.admissionController.validating.annotations }}
  annotations:
{{ toYaml .Values.admissionController.validating.annotations | indent 4 }}
{{- end }}
  namespace: {{ .Values.global.namespace }}
  name: {{ template "opa.fullname" . }}-cert
  labels:
    app: {{ template "opa.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  tls.crt: {{ .Values.cert }}
  tls.key: {{ .Values.key }}


