{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
  namespace: {{ .Values.global.namespace }}
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: {{ .Values.tls.type }}
{{- end }}
