apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: {{ .Values.vs.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  host: {{ .Values.vs.host }}
  policies:
  - name: {{ .Values.ipPolicy.name }}
  tls:
    secret: {{ .Values.tls.name }}
  upstreams:
  - name: {{ .Values.opa.fullnameOverride }}
    service: {{ .Values.opa.fullnameOverride }}
    port: {{ .Values.opa.port }}
  routes:
    - path: {{ .Values.vs.path }}
      action:
        pass: {{ .Values.opa.fullnameOverride }}