{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opa.serviceAccountName" .}}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "opa.fullname" . }}
    chart: {{ template "opa.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
