apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "bundle-server-chart.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "bundle-server-chart.deployment.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bundle-server-chart.deployment.labels" . | nindent 8 }}
    spec:
      containers:
      - name: server
        image: {{ .Values.deployment.image.repo }}:{{ .Values.deployment.image.version }} 
        command: ["/bin/bash"]
        args: ["-c", "cd /bundle-files && for file in *; do base64 -d $file > /usr/share/nginx/html/$file; done && /docker-entrypoint.sh nginx -g 'daemon off;'"]
        ports:
        - containerPort: {{ .Values.deployment.port }}
        volumeMounts:
        - mountPath: {{ .Values.deployment.volume.app.path }}
          name: {{ .Values.deployment.volume.app.name }}
      volumes:
      - name: {{ .Values.deployment.volume.app.name }}
        configMap:
          name: {{ .Values.configmap.name}}
          items:
          - key: {{ .Values.configmap.bundle.key }}
            path: {{ .Values.configmap.bundle.path }}
