apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }} 
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- include "bundle-server-chart.service.labels" . | nindent 6 }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    