name: opa_helm_chart_release
on:
  push:
    paths-ignore:
      - "docs/**"
      - "logo/**"
      - "examples/**"
      - "**.md"
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Publish Helm chart
        run: |
          build/helm-gh-pages.sh "${{ secrets.GITHUB_TOKEN }}" "" "" "" "" "" "charts" "" "off"
